(defproject ngontinh "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [compojure "1.1.7"]
                 [org.apache.commons/commons-pool2 "2.2"]
                  [redis.clients/jedis "2.4.2"]
                  [org.postgresql/postgresql "9.3-1101-jdbc41"]
                  [org.clojure/core.cache "0.6.3"]
                  [cheshire "5.3.1"]

        				[org.apache.lucene/lucene-analyzers-phonetic "4.8.1"]
        				[org.apache.lucene/lucene-classification "4.8.1"]
        				[org.apache.lucene/lucene-grouping "4.8.1"]
        				[org.apache.lucene/lucene-expressions "4.8.1"]
        				[org.apache.lucene/lucene-misc "4.8.1"]
        				[org.apache.lucene/lucene-analyzers-morfologik "4.8.1"]
        				[org.apache.lucene/lucene-analyzers-common "4.8.1"]
                [org.apache.lucene/lucene-benchmark "4.8.1"]
                [org.apache.lucene/lucene-analyzers-icu "4.8.1"]			
                [org.apache.lucene/lucene-spatial "4.8.1"]
                [org.apache.lucene/lucene-highlighter "4.8.1"]
                [org.apache.lucene/lucene-demo "4.8.1"]
                [org.apache.lucene/lucene-codecs "4.8.1"]
                [org.apache.lucene/lucene-sandbox "4.8.1"]
                [org.apache.lucene/lucene-analyzers-stempel "4.8.1"]
                [org.apache.lucene/lucene-queryparser "4.8.1"]
                [org.apache.lucene/lucene-memory "4.8.1"]
                [org.apache.lucene/lucene-analyzers-smartcn "4.8.1"]
                [org.apache.lucene/lucene-replicator "4.8.1"]
                [org.apache.lucene/lucene-queries "4.8.1"]
                [org.apache.lucene/lucene-facet "4.8.1"]
                [org.apache.lucene/lucene-core "4.8.1"]
                [org.apache.lucene/lucene-suggest "4.8.1"]
                [org.apache.lucene/lucene-join "4.8.1"]
                [org.apache.lucene/lucene-analyzers-kuromoji "4.8.1"]]
  :plugins [[lein-ring "0.8.10"]]
  :ring {:handler ngontinh.handler/app}
  :profiles
  {:dev {:dependencies [[javax.servlet/servlet-api "2.5"]
                        [ring-mock "0.1.5"]]}})
